export enum LangKey {
  // common
  COPY_SUCCESS = 'COPY_SUCCESS',
  COPY_FAILED = 'COPY_FAILED',
  NOTICE = 'NOTICE',
  LOADING = 'LOADING',
  PLEASE_CONTACT_THE_ADMINISTRATOR = 'PLEASE_CONTACT_THE_ADMINISTRATOR',
  PLEASE_READ_THE_RELEASE_NOTICE_FIRST = 'PLEASE_READ_THE_RELEASE_NOTICE_FIRST',
  INFORMATION_SAVE_SUCCESS = 'INFORMATION_SAVE_SUCCESS',
  PLEASE_CHECK_NETWORK_OR_DO_REFRESH = 'PLEASE_CHECK_NETWORK_OR_DO_REFRESH',

  // login
  LOGIN_NOTICE = 'LOGIN_NOTICE',
  LOGIN_OUT_NOTICE = 'LOGIN_OUT_NOTICE',
  LOGIN_BE_OVERDUE_NOTICE = 'LOGIN_BE_OVERDUE_NOTICE',
  LOGIN_FAILED_TITLE = 'LOGIN_FAILED_TITLE',
  LOGIN_SUCCESS_TITLE = 'LOGIN_SUCCESS_TITLE',
  LOGIN_CANCEL_TITLE = 'LOGIN_CANCEL_TITLE',
  GET_PUBLIC_USER_INFO = 'GET_PUBLIC_USER_INFO',
  GET_PUBLIC_USER_INFO_CONTENT = 'GET_PUBLIC_USER_INFO_CONTENT',
  GET_USER_PROFILE_INFO_DESC = 'GET_USER_PROFILE_INFO_DESC',
  LOGIN_BE_OVERDUE = 'LOGIN_BE_OVERDUE',
  NOT_LOGGED_IN = 'NOT_LOGGED_IN',

  // update
  UPDATE_NOTICE_TITLE = 'UPDATE_NOTICE_TITLE',
  UPDATE_NOTICE_FAILED_CONTENT = 'UPDATE_NOTICE_FAILED_CONTENT',
  UPDATE_NOTICE_READY_CONTENT = 'UPDATE_NOTICE_READY_CONTENT'
}
